// <auto-generated />
using System;
using AdministracionDePaqueteria;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdministracionDePaqueteria.Migrations
{
    [DbContext(typeof(PaquetesContext))]
    partial class PaquetesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdministracionDePaqueteria.Models.Paquete", b =>
                {
                    b.Property<long>("codRastreo")
                        .HasColumnType("bigint");

                    b.Property<string>("areaServicio")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("estadoActual")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("fechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("idPaquete")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("numPieza")
                        .HasColumnType("int");

                    b.HasKey("codRastreo");

                    b.ToTable("Paquete", t =>
                        {
                            t.HasTrigger("Algun Trigger");
                        });
                });

            modelBuilder.Entity("AdministracionDePaqueteria.Models.estadosPaquete", b =>
                {
                    b.Property<int>("idEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEstado"));

                    b.Property<string>("areaServicio")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<long>("codRastreo")
                        .HasColumnType("bigint");

                    b.Property<string>("estadoActual")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("fechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("idPaquete")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("numPieza")
                        .HasColumnType("int");

                    b.HasKey("idEstado");

                    b.HasIndex("codRastreo");

                    b.ToTable("estadosDelPaquete", (string)null);
                });

            modelBuilder.Entity("AdministracionDePaqueteria.Models.estadosPaquete", b =>
                {
                    b.HasOne("AdministracionDePaqueteria.Models.Paquete", "Paquetes")
                        .WithMany("EstadosPaquetes")
                        .HasForeignKey("codRastreo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paquetes");
                });

            modelBuilder.Entity("AdministracionDePaqueteria.Models.Paquete", b =>
                {
                    b.Navigation("EstadosPaquetes");
                });
#pragma warning restore 612, 618
        }
    }
}
